---
development:
  cloud_name: diqbv9mec
  api_key: '823437676187318'
  api_secret: RGgp7GgCbmFhf-9TD4QKOGKLdTs
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: diqbv9mec
  api_key: '823437676187318'
  api_secret: RGgp7GgCbmFhf-9TD4QKOGKLdTs
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: diqbv9mec
  api_key: '823437676187318'
  api_secret: RGgp7GgCbmFhf-9TD4QKOGKLdTs
  enhance_image_tag: true
  static_image_support: false
