default_twitter: &default_twitter
  twitter_api_key: 'GLWB1wtcZoAuNHplA2GPK2JBa'
  twitter_api_secret: 'GRJym9ouRDTtnk0iQsEP1p3K0qBMt8cWR6FpKgUi83fYA3HyNL'
default_facebook: &default_facebook
  facebook_api_key:'1579231198992498'
  facebook_api_secret: 'ba65db3bdb391c3eb8243053c17ba9fb'
# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c447a65e07e598d79663b676d9f0d175c1b1198e7bbb37da3fd768357bcff6372653c565355180f991d18ca7a02500c429706929b021d7761301565cf5532b9
  <<: *default_twitter
  <<: *default_facebook
test:
  secret_key_base: d09b7d2a5a89e806a3bb7555b5c7c9110fa6996586d216986d4441d2ff3137a1d0f69eb0a26d6c4ae90e33a46138c0b5506f5776db74ba93a79536733c95800b
  <<: *default_twitter
  <<: *default_facebook
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
  facebook_api_key: <%= ENV["FACEBOOK_CONSUMER_KEY"] %>
  facebook_api_secret: <%= ENV["FACEBOOK_CONSUMER_SECRET"] %>